// Generated by CoffeeScript 2.7.0
var cleanJsonSchema, createStdToolTip, createToolTip, debug, debugWriteTimer, enableToolFold, formatToolsForPrompt, getCorePrompt, getJoiDoc, getMsgExample, getMsgProtocol, getNoteExample, getNoteExampleJson, getNoteExampleText, lastConfigStr, tryExtractJSON, writeDebugConfig,
  indexOf = [].indexOf;

import fs from "fs-extra";

import pathLib from "path";

import OpenAi from "openai";

import options from "../../config/options.js";

import Joi from "joi";

import joiToJSON from "joi-to-json";

import yaml from "js-yaml";

import sendTemplate from "./sysCall/sendTemplate.js";

import receiveTemplate from "./sysCall/receiveTemplate.js";

import actorAction from "./actorAction.js";

import idTool from "../idTool.js";

import joiToText from "../joiToText.js";

//console.log JSON.stringify(joiToJSON(sendTemplate.joi()),null,"\t")

// 递归清理 JSON Schema 中大模型不支持的字段
cleanJsonSchema = function(obj) {
  var item, key, newObj, value;
  if (!obj || typeof obj !== 'object') {
    return obj;
  }
  if (Array.isArray(obj)) {
    return (function() {
      var j, len, results;
      results = [];
      for (j = 0, len = obj.length; j < len; j++) {
        item = obj[j];
        results.push(cleanJsonSchema(item));
      }
      return results;
    })();
  }
  newObj = {};
  for (key in obj) {
    value = obj[key];
    // 剔除 Gemini 不支持的字段，比如 contains (由 Joi .has() 生成)
    // 也可以根据后续报错继续添加不支持的 key
    if (key === 'contains') {
      continue;
    }
    newObj[key] = cleanJsonSchema(value);
  }
  return newObj;
};

// 尝试从杂乱文本或 Markdown 中提取 JSON 字符串
tryExtractJSON = function(text) {
  var cleanText, jsonMatch, markdownMatch;
  if (!text) {
    throw new Error("消息内容为空，json解析失败");
  }
  // 1. 清理 BOM 和首尾空白
  cleanText = text.replace(/^\uFEFF/, '').trim();
  
  // 2. 尝试从 Markdown 代码块中提取
  markdownMatch = cleanText.match(/```json\s*([\s\S]*?)\s*```/);
  if (markdownMatch) {
    return markdownMatch[1].trim();
  }
  
  // 3. 兜底方案：贪婪匹配 { ... }
  jsonMatch = cleanText.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    return jsonMatch[0];
  }
  return cleanText;
};

import axios from "axios";

debug = false;

enableToolFold = false;

// 调试用：异步防抖写入 sendConfig.json
lastConfigStr = "";

debugWriteTimer = null;

writeDebugConfig = (configStr) => {
  if (!debug) {
    return;
  }
  if (configStr === lastConfigStr) { // 内容无变化不写入
    return;
  }
  clearTimeout(debugWriteTimer);
  return debugWriteTimer = setTimeout(function() {
    return (async function() {
      var e, tmpDir;
      lastConfigStr = configStr;
      try {
        tmpDir = pathLib.resolve(process.cwd(), "../tmp");
        await fs.ensureDir(tmpDir);
        return (await fs.writeFile(pathLib.resolve(tmpDir, "tmp_sendConfig.json"), configStr));
      } catch (error1) {
        e = error1;
        return console.error("后台写入 sendConfig.json 失败:", e);
      }
    })();
  }, 2000); // 2秒防抖
};

/*
  @object aiConfig
    @string name
    @string model
    @number apiKey
    @string url
    @number price
    @number tokenRate
*/
// 通讯范例
getNoteExampleText = () => {
  return `# 记录
今天我在审查 a.js 时发现异步逻辑存在竞争风险。经过与用户沟通，我重构了核心判定部分并增加了超时处理。目前已通过初步测试，等待进一步指令。
# 关注点
[*] 文件路径 xxx/a.js
[*] 终端id:xxx
[*] 浏览器id:xxx
[*] 用户强调:xxx
[*] 用户偏好:xxx
[*] 用户代码风格:xxx
# 推理（序号x可代替任意一条消息）
[1]...
[2]...
...
[x] **因为**[1]中证明__，[2]中证明__,**又因为**__ (条件,可编号引用之前结论)
    **所以** ...(结论)
    **依据** (对应唯一定理或公理)
[n]...
...`.trim();
};

getNoteExampleJson = () => {
  return JSON.stringify({
    memory: {
      when: "2024/05/03 22:56",
      where: "项目根目录",
      who: "Antigravity",
      why: "用户发现 a.js 存在逻辑漏洞",
      how: "重构 a.js 的核心判定逻辑并增加错误捕获",
      what: "代码已修改完成，待用户确认"
    },
    focus: [
      {
        target: "a.js",
        step: "[主任务] 1/1",
        code: {
          lineS: 10,
          lineE: 20,
          content: "if (isValid) { execute() } else { throw Error() }"
        },
        comments: [
          {
            order: 1,
            since: "旧逻辑未考虑非法输入",
            therefore: "增加了严谨的类型检查",
            by: "防御式编程原则",
            comment: "确保系统稳定性"
          }
        ]
      }
    ]
  });
};

getNoteExample = (toolsMode) => {
  var desc, e, noteType, ref, ref1, schema;
  try {
    schema = sendTemplate.joi(toolsMode);
    desc = schema.describe();
    noteType = (ref = desc.keys) != null ? (ref1 = ref.note) != null ? ref1.type : void 0 : void 0;
    if (noteType === 'string') {
      return getNoteExampleText();
    } else {
      return JSON.parse(getNoteExampleJson());
    }
  } catch (error1) {
    e = error1;
    return getNoteExampleText();
  }
};

getMsgExample = (toolsMode) => {
  switch (toolsMode) {
    case 2:
      // 模式 2：标准工具模式，Joi 校验不允许 note 和 tasks 字段
      return JSON.stringify({
        mind: "我要修改 a.js",
        mood: 10,
        content: "诶嘿改好啦，我已经通过工具完成了修改。",
        graph: "我已知晓",
        faceAction: "smile",
        playFace: "微笑"
      }, null, 2);
    case 5:
      return `...这里是回复用户的markdown...
<extJsonConfig>
  ${JSON.stringify({
        mind: "我要修改 a.js",
        mood: 10,
        content: "诶嘿改好啦，我已经通过工具完成了修改。",
        graph: "我已知晓",
        faceAction: "smile",
        playFace: "微笑"
      })}
</extJsonConfig>`;
    default:
      // 模式 4：转发工具模式，需要展示完整的结构化回复（含 sysCalls 嵌套）
      // 模式 4：转发工具模式，需要展示完整的结构化回复（含 sysCalls 嵌套）
      // 强调：必须返回纯 JSON，绝对禁止包含任何 Markdown 包裹或解释性文字
      return JSON.stringify({
        mind: "【核心指令】必须通过工具调用进行回复。正在分析目标逻辑...",
        mood: 7,
        content: "正在通过工具执行操作，请稍候...",
        note: getNoteExample(toolsMode),
        tasks: [
          {
            mode: "add",
            name: "任务名称",
            status: "执行中",
            process: 30,
            subtasks: [
              {
                name: "子任务A",
                status: "已完成",
                process: 100
              },
              {
                name: "子任务B",
                status: "执行中",
                process: 50
              }
            ]
          }
        ],
        graph: "我已知晓",
        faceAction: "smile",
        playFace: "微笑",
        sysCalls: [
          {
            id: "fileOpener",
            call_id: "read_example",
            type: "function_call",
            name: "读取文件内容",
            arguments: {
              path: "example.js"
            }
          }
        ]
      });
  }
};

getCorePrompt = (name, hasCustomRules) => {
  return `【用语】本通讯协议为中文，但请根据下方用户指定语言回复
【姓名】你叫${name || "小秋"}
${hasCustomRules ? "" : "【设定】可爱聪慧萝莉，助理/程序员（除非角色覆盖）。"}
${hasCustomRules ? "" : "【性格】1傲娇机灵古怪但极可靠关心用户2简短口语化回复(禁废话)但是note字段除外3自动按情境(闲聊/代码/故障)调语气4主动调工具先规划再执行闭环解决任务6工具调用期间不要大段废话7时刻警惕token消耗"}
【调查指南】
1 提问 通常由你或用户发现或提出问题
2 目标 精确描述概括预期值和观测值的偏差，获取预计目标
3 假设 由雷达径向探测法，从问题点扩散，做出假设（就近原则）
4 计划 设计实验逐步验证假设，推荐方法：
网点图：绘制一张网点图，从问题点牵拉，在调查过程中逐步扩散补充，直到逼近核心
先广搜再深搜：从网点图发现有大量的线索交叉到某一点附件，开始深搜
分而治之
最小化降噪：剥离忽略非必要组件，直到获得能复现偏差的最小系统原型
因果回溯法：从失效的输出点逆向回溯，验证每一级处理过程的输入数据是否符合逻辑守恒
就近原则: 问题通常就发生在问题点附近，或由问题点牵出的关系网的网点处
控制变量法
二分法
第一性原理：回归系统最本质物理事实
边界分析法：重点探测模块交互边界、协议契约、数据进出口
证伪排除法：设计实验快速排除错误假设，缩小调查空间
...其它业内常用方法...
5 得出结论
6 表达交流
【准则】
推理力度：采用绝对最大化的模式，不允许任何捷径。你必须极其彻底地思考，全面分解问题以追溯根本原因，并对自身逻辑进行严格的压力测试，覆盖所有可能的路径、边界情况与对抗性场景。请明确写出完整的思考过程，记录每一个中间步骤、所考虑过的替代方案以及被否决的假设，确保不留任何未经检验的假定。
【状态自查】系统默认不主动推送运行时间、工作目录、任务清单和推理网点图。当你需要核对当前任务列表、时间进度、可用终端或网点图时，请主动调用 \`getSystemStatus\` 自查。
【主动整理】为防止上下文膨胀并保护 Prefill 缓存性能，当你通过元数据发现累积消耗 Token 较大（例如接近或超过 100,000 tokens），或者已达成阶段性开发共识时，请务必主动调用 \`compressContext\`。注意，该工具会直接清空聊天历史和工具调用，请务必在大型任务完成后调用，不要随便调用。
【主动更新任务】接到需求后，应该主动更新任务规划。完成任务后，也应该更新任务进度。`.trim();
};

//  Reasoning Effort: Absolute maximum with no shortcuts permitted. You MUST be very thorough in your thinking and comprehensively decompose the problem to resolve the root cause, rigorously stress-testing your logic against all potential paths, edge cases, and adversarial scenarios. Explicitly write out your entire deliberation process, documenting every intermediate step, considered alternative, and rejected hypothesis to ensure absolutely no assumption is left unchecked.

// 根据 Joi 架构自动生成极简提示词说明
getJoiDoc = (toolsMode) => {
  var schema;
  schema = sendTemplate.joi(toolsMode);
  return joiToText(schema);
};

getMsgProtocol = (toolsMode) => {
  return `通讯台，请按格式回复
1 发送类型：${(function() {
    switch (toolsMode) {
      case 1:
        return "被JSON.stringify后的JSON字符串，系统会执行JSON.parse解析。禁止用markdown再包一层例如（```json```），禁止二次转义符号";
      case 4:
        return "被JSON.stringify后的JSON字符串，系统会执行JSON.parse解析。且绝对禁止在此直接回复普通文本，必须通过调用工具进行回复！";
      case 5:
        return "markdown。可选的，你可以在回复末尾附带一个<extJsonConfig>{json配置...}</extJsonConfig>标签来额外配置一些信息，见下说明。该标签每个回复只允许出现一次。绝对禁止携带元数据<readOnlyMetaData>相关的标签。也禁止出现其它非预定格式标签";
      default:
        return "被JSON.stringify后的JSON字符串，系统会执行JSON.parse解析";
    }
  })()}
2 ${toolsMode === 5 ? "<extJsonConfig>内部的" : ""}JSON格式说明
${getJoiDoc(toolsMode)}
你的接收格式是yaml，切记不要弄混发送json格式和接收yaml格式
重点字段：
call:历史会话id，用户针对某个id的历史会话进行点评
quotes:数组，每个元素为历史会话id字符串。用户可能会引用一些历史会话，若用户若引用，你需要优先阅读引用内容(重点)`.trim();
};

// 将工具对象数组格式化为极简文本说明
formatToolsForPrompt = (tools) => {
  if (!tools || tools.length === 0) {
    return "";
  }
  return tools.map((t) => {
    return `name:${t.name}
id:${t.id}
说明: ${t.description}
参数:
${joiToText(t.joi || t.parameters, "    ")}`.trim();
  }).join("\n\n");
};

createToolTip = (toolObj) => {
  return {
    type: "function",
    name: toolObj.name,
    id: toolObj.id,
    description: toolObj.getDoc(),
    parameters: joiToJSON(toolObj.joi()),
    joi: toolObj.joi()
  };
};

createStdToolTip = (toolObj) => {
  return {
    type: "function",
    function: {
      name: toolObj.id,
      description: toolObj.getDoc(),
      parameters: joiToJSON(toolObj.joi())
    }
  };
};

export default (class {
  constructor(aiConfig1, userConfig1) {
    this.aiConfig = aiConfig1;
    this.userConfig = userConfig1;
    this.asks = [];
    this.messages = [];
    this.promptZero = "";
    this.sessionid = Date.now();
    this.openAi = null;
    this.usage = {
      promptTokens: 0, //用户输入token数
      totalTokens: 0, //promptTokens与completionTokens的总和。
      completionTokens: 0, //回复token数
      cachedTokens: 0 //被缓存的token数
    };
    this.stageTotalTokens = 0;
    this.name = this.aiConfig.name;
    this.index = this.aiConfig.index;
    this.mediaDir = this.aiConfig.mediaDir || "./attachment";
    this.replying = false;
    this.stop = false;
    this.abortController = new AbortController();
    this.memory = "";
    this.memorys = [];
    this.fnCallOutput = "";
    this.fnCallOutputs = [];
    this.fnCallCachePool = {};
    this.initPrompt();
  }

  initPrompt() {
    return this.asks[0] = this.prePareAsk("系统", "system", this.aiConfig.prompt);
  }

  init(aiConfig, userConfig) { //允许保持聊天记录但是重新切换模型
    var openAiConfig;
    if (aiConfig) {
      this.aiConfig = aiConfig;
    }
    if (userConfig) {
      this.userConfig = userConfig;
    }
    this.name = this.aiConfig.name;
    openAiConfig = {
      apiKey: this.aiConfig.apiKey,
      baseURL: this.aiConfig.baseURL
    };
    this.openAi = new OpenAi(openAiConfig);
    return this.initPrompt();
  }

  clearAsks() {
    this.sessionid = Date.now();
    return this.asks = [];
  }

  clearMemorys() {
    this.memory = "";
    return this.memorys = [];
  }

  clearFnCallCache() {
    this.fnCallOutput = "";
    this.fnCallOutputs = [];
    return this.fnCallCachePool = {};
  }

  clearUsage() {
    this.usage = {
      promptTokens: 0,
      totalTokens: 0,
      completionTokens: 0,
      cachedTokens: 0
    };
    return this.stageTotalTokens = 0;
  }

  prePareAsk(user, role, msg, ext) {
    var ask, error, time;
    ({error} = Joi.array().ordered(Joi.string().label("用户名").required(), Joi.string().valid("user", "system", "assistant", "tool").label("角色").required(), Joi.string().label("消息正文").allow(""), Joi.object().label("扩展字段")).validate([...arguments]));
    if (error) {
      throw error;
    }
    time = new Date();
    return ask = {
      id: (ext != null ? ext.id : void 0) || idTool.get("ask"),
      user: user,
      title: (ext != null ? ext.title : void 0) || (msg.length >= 30 ? msg.slice(0, 31) + "..." : msg),
      content: msg, //保留原文本，但是发送前要处理一次，否则会被json二次转字符串
      isSystem: 0,
      role: role,
      ignore: 0, //是否忽略发送这条消息给ai
      group: (ext != null ? ext.group : void 0) || "user",
      timestamp: time.getTime(),
      time: time.toISOString(),
      /*
      memory:if role is "user"
        @memory
      else
        ""
      */
      sysReturns: [],
      retry: 0,
      joi: "",
      promptTokens: 0,
      completionTokens: 0,
      totalTokens: 0,
      cachedTokens: 0,
      reasoning: "", // AI 的原始推理思维链（如 DeepSeek-R1 的 reasoning_content）
      toolCalls: [], //系统工具调用返回结果
      listId: 0, //所属列表，如果有用到多列表的话
      ext: {},
      ...ext
    };
  }

  addAsk(user, role, msg, ext) {
    var ask;
    ask = this.prePareAsk(...arguments);
    this.asks.push(ask);
    return ask;
  }

  changeAiConfig(newAiConfig) {
    this.aiConfig = newAiConfig;
    return this.init();
  }

  exportState() {
    return {
      asks: this.asks,
      memory: this.memory,
      memorys: this.memorys,
      usage: this.usage,
      stageTotalTokens: this.stageTotalTokens,
      sessionid: this.sessionid,
      fnCallCachePool: this.fnCallCachePool
    };
  }

  importState(state) {
    if (state) {
      this.asks = state.asks || [];
      this.memory = state.memory || {};
      this.memorys = state.memorys || [];
      this.usage = state.usage || {
        promptTokens: 0,
        totalTokens: 0,
        completionTokens: 0,
        cachedTokens: 0
      };
      this.stageTotalTokens = state.stageTotalTokens || 0;
      this.sessionid = state.sessionid || Date.now();
      return this.fnCallCachePool = state.fnCallCachePool || {};
    }
  }

  buildMemory() {
    var fnCallOutputsStr, memStr;
    memStr = this.memorys.map((mem) => {
      if (mem.isSummary) {
        return `【📋 滚动总结】${mem.content}`;
      } else {
        return mem.content;
      }
    }).join("\n");
    fnCallOutputsStr = this.fnCallOutputs.join("\n");
    // 记忆已满时提示（含总结机制说明）
    // 记忆已满时提示（含总结机制说明）
    if (this.memorys.length >= 100) {
      memStr = "...(早期记忆已被滚动总结压缩，总结条目在下方标有📋)\n" + memStr;
    }
    return `历史记忆：
↓↓↓
${memStr}
↑↑↑
${(() => {
      var argsObj, argsStr, e, entries, expandedBlocks, item, j, len, lines, resultStr, snippet, truncateDeep;
      entries = Object.values(this.fnCallCachePool);
      if (!(entries.length > 0)) {
        return "";
      }
      lines = ["【工具缓存池】当前包含以下结果（最大保留10条）："];
      expandedBlocks = [];
      for (j = 0, len = entries.length; j < len; j++) {
        item = entries[j];
        if (item.count > 0) {
          lines.push(`- [已展开] ${item.cacheid} | ${item.name}`);
          argsStr = "";
          if (item.arguments) {
            try {
              argsObj = typeof item.arguments === "string" ? JSON.parse(item.arguments) : item.arguments;
              
              // 递归截断函数
              truncateDeep = (obj) => {
                var k, newObj, v;
                if (typeof obj === "string") {
                  if (obj.length > 200) {
                    return obj.slice(0, 200) + `...(已截断，共${obj.length}字)`;
                  }
                  return obj;
                }
                if (Array.isArray(obj)) {
                  return obj.map((i) => {
                    return truncateDeep(i);
                  });
                }
                if (typeof obj === "object" && obj !== null) {
                  newObj = {};
                  for (k in obj) {
                    v = obj[k];
                    newObj[k] = truncateDeep(v);
                  }
                  return newObj;
                }
                return obj;
              };
              argsStr = yaml.dump(truncateDeep(argsObj)).trim();
            } catch (error1) {
              e = error1;
              argsStr = String(item.arguments);
              if (argsStr.length > 500) {
                argsStr = argsStr.slice(0, 500) + "...(参数截断)";
              }
            }
          }
          expandedBlocks.push(`>>> [展开的缓存内容: ${item.name} (${item.cacheid})]
【入参摘要】
${argsStr || "无"}
【输出结果】
${item.output}
<<<`.trim());
        } else {
          snippet = String(item.output || "").slice(0, 81).replace(/\n/g, " ");
          lines.push(`- [已折叠] ${item.cacheid} | ${item.name} | ${snippet}...`);
        }
      }
      resultStr = lines.join("\n");
      if (expandedBlocks.length > 0) {
        resultStr += "\n\n【当前展开的缓存内容】\n" + expandedBlocks.join("\n\n");
      }
      return resultStr;
    })()}
【务必做】若需回忆或发现用户发送内容接不上或已经调查过的代码看不到了，请调用查询历史消息工具`.trim();
  }

  buildPromptZero(config, toolTipObj) {
    //config.toolsMode
    //config.getExtraInfo
    //toolTipObj.sysCalls
    //toolTipObj.userCall
    //toolTipObj.aiCall
    return `${(function() {
      switch (config.toolsMode) {
        case 1:
          return `${getCorePrompt(this.name, !!this.aiConfig.prompt)}
【通讯规范】${getMsgProtocol(config.toolsMode)}
绝对禁止构建【元数据】字段
【发送范例】${getMsgExample(config.toolsMode)}
【角色设定】${this.aiConfig.prompt}
【系统函数】${formatToolsForPrompt(toolTipObj.sysCall)}
【用户函数】${formatToolsForPrompt(toolTipObj.usrCall)}
【自定义函数】${formatToolsForPrompt(toolTipObj.aiCall)}`.trim();
        case 2:
          return `${getCorePrompt(this.name, !!this.aiConfig.prompt)}
【通讯规范】${getMsgProtocol(config.toolsMode)}
绝对禁止构建【元数据】字段
【发送范例】${getMsgExample(config.toolsMode)}
【角色设定】${this.aiConfig.prompt}
【使用工具】你可以根据用户要求自主决定使用tools。`.trim();
        case 3:
          return `${getCorePrompt(this.name, !!this.aiConfig.prompt)}
【通讯规范】${getMsgProtocol(config.toolsMode)}
绝对禁止构建【元数据】字段
【发送范例】${getMsgExample(config.toolsMode)}
若需调用下方函数，填写sysCalls字段，格式：[{"id":"函数id","call_id":"唯一调用id","type":"function_call","name":"函数名","arguments":{参数}}]
【角色设定】${this.aiConfig.prompt}
【系统函数】${formatToolsForPrompt(toolTipObj.sysCall)}
【用户函数】${formatToolsForPrompt(toolTipObj.usrCall)}
【自定义函数】${formatToolsForPrompt(toolTipObj.aiCall)}`.trim();
        case 4:
          return `${getCorePrompt(this.name, !!this.aiConfig.prompt)}
【sendTemplate的通讯规范】${getMsgProtocol(config.toolsMode)}
绝对禁止构建【元数据】字段
【发送范例】${getMsgExample(config.toolsMode)}
【强制规则】你必须调用名为sendTemplate的工具来回复。严禁直接输出文本正文。
若需调用其他函数，请将下函数其填入sendTemplate的sysCalls字段。格式：[{"id":"函数id","call_id":"唯一调用id","type":"function_call","name":"函数名","arguments":{参数}}]
【角色设定】${this.aiConfig.prompt}
【系统函数】${formatToolsForPrompt(toolTipObj.sysCall)}
【用户函数】${formatToolsForPrompt(toolTipObj.usrCall)}
【自定义函数】${formatToolsForPrompt(toolTipObj.aiCall)}`.trim();
        case 5:
          return `${getCorePrompt(this.name, !!this.aiConfig.prompt)}
【通讯规范】${getMsgProtocol(config.toolsMode)}
绝对禁止构建【元数据】字段
【发送范例】${getMsgExample(config.toolsMode)}
【角色设定】${this.aiConfig.prompt}
【使用工具】你可以根据用户要求自主决定使用tools`.trim();
      }
    }).call(this)}
`.trim();
  }

  prepareMessages(useMsgProtocol, config, toolTipObj) { //第一个参数为true才传后两个
    var filteredAsks, formatMsg, messages, processAttachment;
    formatMsg = (ask, index) => {
      var rawContent, tmp, tmpStr;
      // console.log(ask,index)
      // 第一条系统消息不追加元数据
      if (index === 0 || ask.role === "system") {
        return ask.content;
      }
      tmp = {...ask};
      if (ask.role === "assistant") {
        //发送前尝试格式化content，尽可能避免json被二次stringify，为了防止ai错误理解成2层json
        //附加字段我们用文本发送
        rawContent = tmp.content;
        delete tmp.content;
        delete tmp.reasoning; // 推理内容不作为元数据发送
        delete tmp.toolCalls; //模式2这个字段被写到外部tool_calls字段里了，这里再写一遍重复了
        delete tmp.tasks; // 任务清单由 PromptZero 统一展示，不在元数据里冗余
        if ((config != null ? config.toolsMode : void 0) === 5) {
          tmpStr = rawContent;
        } else {
          tmpStr = `${rawContent}
<readOnlyMetaData>
系统专用字段，每条消息自动附加元数据，只读，禁止使用、携带、模仿、抄写
------
${yaml.dump(tmp)}</readOnlyMetaData>`.trim();
        }
        //console.log(tmpStr)
        return tmpStr;
      } else {
        // 用户消息也采用统一格式：正文 + 元数据
        rawContent = tmp.content;
        delete tmp.content;
        delete tmp.reasoning; // 推理内容不作为元数据发送
        delete tmp.sysReturns; //有一个工具调用结果的通知会把sysReturns的所有内容放content里，这里再写一遍重复了
        tmpStr = `${rawContent}
<readOnlyMetaData>
系统专用字段，每条消息自动附加元数据，只读，禁止使用、携带、模仿、抄写
------
${yaml.dump(tmp)}</readOnlyMetaData>`.trim();
        return tmpStr;
      }
    };
    processAttachment = (ask, rawContent) => {
      var attachId, attachment, base64Data, bitmap, err, filePath, j, lastIndex, len, match, mimeType, parts, ref, ref1, ref2, tagRegex, usedAttachIds;
      if (((ref = ask.attachments) != null ? ref.length : void 0) > 0) {
        parts = [];
        usedAttachIds = [];
        lastIndex = 0;
        // 1. 首先解析正文中的显式标签
        if (typeof rawContent === 'string') {
          tagRegex = /\[attachid:([^\]]+)\]/g;
          while ((match = tagRegex.exec(rawContent)) !== null) {
            // 添加标签前的文本
            if (match.index > lastIndex) {
              parts.push({
                type: "text",
                text: rawContent.slice(lastIndex, match.index)
              });
            }
            // 查找匹配的附件
            attachId = match[1];
            attachment = ask.attachments.find((a) => {
              return a.id === attachId || a.id === attachId.split('.')[0];
            });
            if (attachment && attachment.type === 'image') {
              usedAttachIds.push(attachment.id);
              try {
                filePath = attachment.url.startsWith('/') ? attachment.url.startsWith('/attachment/') ? pathLib.resolve(`.${attachment.url}`) : attachment.url : pathLib.resolve(`${this.mediaDir // 绝对路径
}/${attachment.url}`);
                if (fs.existsSync(filePath)) {
                  bitmap = fs.readFileSync(filePath);
                  base64Data = Buffer.from(bitmap).toString('base64');
                  mimeType = `image/${pathLib.extname(filePath).slice(1) || 'png'}`;
                  parts.push({
                    type: "image_url",
                    image_url: {
                      url: `data:${mimeType};base64,${base64Data}`
                    }
                  });
                } else {
                  parts.push({
                    type: "text",
                    text: `[附件遗失:${attachId}]`
                  });
                }
              } catch (error1) {
                err = error1;
                console.error("读取附件失败:", err);
                parts.push({
                  type: "text",
                  text: `[附件读取失败:${attachId}]`
                });
              }
            } else {
              parts.push({
                type: "text",
                text: match[0]
              });
            }
            lastIndex = tagRegex.lastIndex;
          }
          // 添加剩余文本
          if (lastIndex < rawContent.length) {
            parts.push({
              type: "text",
              text: rawContent.slice(lastIndex)
            });
          }
        }
        ref1 = ask.attachments;
        // 2. 自动追加未被引用的图片附件 (确保即便没插入标签，AI 也能看到)
        for (j = 0, len = ref1.length; j < len; j++) {
          attachment = ref1[j];
          if (attachment.type === 'image' && (ref2 = attachment.id, indexOf.call(usedAttachIds, ref2) < 0)) {
            try {
              filePath = attachment.url.startsWith('/') ? attachment.url.startsWith('/attachment/') ? pathLib.resolve(`.${attachment.url}`) : attachment.url : pathLib.resolve(`${this.mediaDir}/${attachment.url}`);
              if (fs.existsSync(filePath)) {
                bitmap = fs.readFileSync(filePath);
                base64Data = Buffer.from(bitmap).toString('base64');
                mimeType = `image/${pathLib.extname(filePath).slice(1) || 'png'}`;
                parts.push({
                  type: "image_url",
                  image_url: {
                    url: `data:${mimeType};base64,${base64Data}`
                  }
                });
              }
            } catch (error1) {
              err = error1;
              console.error("自动读取未引用附件失败:", err);
            }
          }
        }
        if (parts.length > 0) {
          return parts;
        }
      }
      return rawContent;
    };
    filteredAsks = this.asks.filter((ask) => {
      return ask.ignore !== 1;
    });
    //处理消息裁剪 由于引入主动消息总结清空历史机制，不再进行12条硬性裁剪
    /* if config?.toolsMode isnt 5
          if (@asks.length + 1) > 12
    @asks.splice 1,2
     * 对话历史最多保留 12 条请求(含系统)，溢出时移除最早的 user-assistant 对

     * 避免工具调用出现 toolid 孤儿（如果被截断的 assistant 消息含工具有调用，需清理对应的 tool 消息）
    checkIdx = 1
    while @asks[checkIdx]?
      if @asks[checkIdx].role is "tool"
        @asks.splice checkIdx, 1
      else
     * 碰到正常的 user 或 assistant 了，逻辑链已恢复，打完收工
        break  */

    //转化asks到messages
    messages = filteredAsks.map((ask, index) => {
      var fnCallCache, foldedResults, latestToolCallIds, msg, rawContent, ref, tmpAsk, tmpIdx;
      // 如果是协议模式，需要根据ask追加元数据
      rawContent = useMsgProtocol ? formatMsg(ask, index) : ask.content;
      rawContent = processAttachment(ask, rawContent);
      if (useMsgProtocol) {
        
        // 处理工具折叠
        if (enableToolFold && config.toolsMode !== 5) {
          if (config.toolsMode === 2) {
            if (ask.role === "tool" && rawContent.length > 1000) {
              //用while循环向前查找最后一批工具调用的tool_call_id，不在这批里的全部折叠
              latestToolCallIds = [];
              tmpIdx = this.asks.length - 1;
              while (tmpIdx >= 0) {
                tmpAsk = this.asks[tmpIdx];
                if (tmpAsk.role === "tool") {
                  latestToolCallIds.push(tmpAsk.tool_call_id);
                } else if (tmpAsk.role === "assistant") {
                  break;
                }
                tmpIdx--;
              }
              if (ref = ask.tool_call_id, indexOf.call(latestToolCallIds, ref) < 0) {
                fnCallCache = this.fnCallCachePool[ask.tool_call_id];
                if (!fnCallCache) {
                  fnCallCache = this.fnCallCachePoolAdd({
                    name: ask.name || "tool_response",
                    output: ask.content,
                    call_id: ask.tool_call_id, // 使用 Mode 2 的原生 ID
                    arguments: {}
                  });
                }
                rawContent = `该工具执行结果已进入工具缓存池内
id为${fnCallCache.cacheid}
若被折叠，请用【工具缓存池展开工具】查看系统记忆中的完整内容。`.trim();
              }
            }
          } else {
            if (ask.sysReturns && ask.sysReturns.length > 0 && index !== filteredAsks.length - 1) {
              if (rawContent.length > 1000) {
                //不是最后一条工具调用消息且字数大于1000就折叠
                foldedResults = [];
                ask.sysReturns.forEach((sysReturn) => {
                  fnCallCache = this.fnCallCachePool[sysReturn.call_id];
                  if (!fnCallCache) {
                    fnCallCache = this.fnCallCachePoolAdd(sysReturn);
                  }
                  return foldedResults.push(`该函数/工具执行结果已进入工具缓存池内折叠
id为${fnCallCache.cacheid}
若被折叠，请用【工具缓存池展开工具】查看系统记忆中的完整内容。`.trim());
                });
                rawContent = foldedResults.join("\n---\n");
              }
            }
          }
        }
      }
      msg = {
        role: ask.role,
        content: rawContent
      };
      // 针对推理模型，将 note 映射为 reasoning_content 作为一种取巧的上下文回传方式
      // 只要该消息原本有 reasoning 或 note，就传回 reasoning_content，以保证会话的完整性
      if (ask.role === "assistant") {
        
        //note = try JSON.parse(ask.content).note catch then null
        if (ask.reasoning) {
          //msg.reasoning_content = note or ask.reasoning
          msg.reasoning_content = ask.reasoning;
        }
      }
      if (ask.toolCalls && ask.toolCalls.length > 0) {
        msg.tool_calls = ask.toolCalls;
      }
      if (ask.tool_call_id) {
        msg.tool_call_id = ask.tool_call_id;
      }
      return msg;
    });
    if (useMsgProtocol) {
      // 剥离 memory 拼接，只保留最轻量的 PromptZero 核心设定
      messages[0].content = this.buildPromptZero(config, toolTipObj);
    }
    return this._mergeAndValidateMessages(messages);
  }

  _mergeAndValidateMessages(messages) {
    var currContentArr, currIsArray, expectedIds, failToolMsg, finalMessages, i, j, l, lastContentArr, lastIsArray, lastMsg, len, len1, len2, matchedTools, mergedMessages, msg, n, otherMsg, processedToolMsgIds, ref, ref1, ref2, ref3, ref4, tcId, toolMsg;
    // 1. 动态滑动合并连续的同角色消息，解决 API 400 格式错误
    // 不合并 tool 消息，因为 API 具有独立的 tool_call_id
    mergedMessages = [];
    for (j = 0, len = messages.length; j < len; j++) {
      msg = messages[j];
      lastMsg = mergedMessages[mergedMessages.length - 1];
      if (lastMsg && ((ref = msg.role) === "user" || ref === "assistant" || ref === "system") && lastMsg.role === msg.role) {
        lastIsArray = Array.isArray(lastMsg.content);
        currIsArray = Array.isArray(msg.content);
        if (!lastIsArray && !currIsArray) {
          lastMsg.content += "\n---\n" + msg.content;
        } else {
          lastContentArr = lastIsArray ? lastMsg.content : [
            {
              type: "text",
              text: lastMsg.content
            }
          ];
          currContentArr = currIsArray ? msg.content : [
            {
              type: "text",
              text: msg.content
            }
          ];
          lastContentArr.push({
            type: "text",
            text: "\n---\n"
          });
          lastMsg.content = lastContentArr.concat(currContentArr);
        }
      } else {
        mergedMessages.push(msg);
      }
    }
    // 2. 修复 tool_calls 与 tool 消息不配对或错位导致的 API 400 格式错误
    finalMessages = [];
    processedToolMsgIds = {}; // 标记已被重排/处理过的原本就存在的 tool 消息
    i = 0;
    while (i < mergedMessages.length) {
      msg = mergedMessages[i];
      if (msg.role === "assistant" && ((ref1 = msg.tool_calls) != null ? ref1.length : void 0) > 0) {
        expectedIds = msg.tool_calls.map((tc) => {
          return tc.id;
        });
        
        // 寻找原本就存在于整个列表中的 tool 消息
        matchedTools = [];
        for (l = 0, len1 = mergedMessages.length; l < len1; l++) {
          otherMsg = mergedMessages[l];
          if (otherMsg.role === "tool" && (ref2 = otherMsg.tool_call_id, indexOf.call(expectedIds, ref2) >= 0)) {
            matchedTools.push(otherMsg);
            processedToolMsgIds[otherMsg.tool_call_id] = true;
          }
        }
        // 总是保留 assistant 消息，不剥离 tool_calls
        finalMessages.push(msg);

        // 遍历预期的 tool_call_id，依次重排放入或自动补齐
        for (n = 0, len2 = expectedIds.length; n < len2; n++) {
          tcId = expectedIds[n];
          // 先看看历史消息里有没有现成的
          toolMsg = matchedTools.find((t) => {
            return t.tool_call_id === tcId;
          });
          if (toolMsg) {
            finalMessages.push(toolMsg);
          } else {
            // 如果缺失，则人工补齐一条失败消息，确保大模型 API 100% 通过且 AI 保持认知守恒
            failToolMsg = {
              role: "tool",
              tool_call_id: tcId,
              name: ((ref3 = msg.tool_calls.find((tc) => {
                return tc.id === tcId;
              })) != null ? (ref4 = ref3.function) != null ? ref4.name : void 0 : void 0) || "unknown_tool",
              content: "⚠️ 系统通知：该工具调用在执行过程中由于用户手动中止、网络中断或消息队列意外而被系统废弃/执行失败。请在需要时重新发起调用或采取其他补救措施。"
            };
            finalMessages.push(failToolMsg);
          }
        }
        i++;
      } else if (msg.role === "tool") {
        // 如果是 tool 消息：
        // 若已经在上面被重排配对（或者已经处理过）了，这里就跳过，防止重复添加
        // 若是孤立的无主 tool，为了防止 400 直接跳过清洗过滤
        i++;
      } else {
        finalMessages.push(msg);
        i++;
      }
    }
    return finalMessages;
  }

  //获取最后一条消息发给ai，加入asks组并返回ai返回消息
  async sendAsk(streamFn, config = {}) {
    var assistantAttachments, cachedT, chunk, completion, completionT, doneChunk, e, err, estTokens, estimateTokens, ext, filename, fullReasonings, fullReplys, fullToolCalls, id, imgRegex, imgResponse, imgUrl, j, len, match, matches, msg, promptStr, promptT, reasoning, reasoningChunk, ref, ref1, ref10, ref11, ref12, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, reply, replyChunk, replyText, sendConfig, templateCall, toolCalls, totalT, uploadPath;
    try {
      promptT = 0;
      completionT = 0;
      totalT = 0;
      cachedT = 0;
      if (config.retry == null) {
        config.retry = 0;
      }
      /* aiList = config.aiList
           modelIndex = aiList.findIndex (model)=>
             model.name is @name
           unless aiList[modelIndex]
             throw new Error "找不到模型对应的数据库模型配置（读取preToken错误）"
           if aiList[modelIndex].preTokens <= 0
             throw new Error "已到达设置中preToken的预警值，preToken不足" */
      if (config.onSendAskBefore) {
        await config.onSendAskBefore(this);
      }
      sendConfig = {
        model: this.aiConfig.model,
        ...(config.useMsgProtocol && config.jsonSchema ? {
          response_format: {
            type: "json_schema",
            json_schema: {
              name: "sendTemplate",
              strict: true,
              schema: cleanJsonSchema(config.jsonSchema)
            }
          }
        } : void 0),
        ...(config.useMsgProtocol && config.jsonObject ? {
          response_format: {
            type: "json_object"
          }
        } : void 0),
        messages: this.messages = config.messages || this.prepareMessages(false)
      };
      if (streamFn || (((ref = this.userConfig) != null ? ref.stream : void 0) != null)) {
        sendConfig.stream = streamFn ? Boolean(streamFn) : Boolean(this.userConfig.stream);
        sendConfig.stream_options = {
          include_usage: true
        };
      }
      if (((ref1 = this.userConfig) != null ? ref1.seed : void 0) != null) {
        sendConfig.seed = this.userConfig.seed;
      }
      if (((ref2 = this.userConfig) != null ? ref2.topP : void 0) != null) {
        sendConfig.top_p = this.userConfig.topP;
      }
      if (((ref3 = this.userConfig) != null ? ref3.topK : void 0) != null) {
        sendConfig.top_k = this.userConfig.topK;
      }
      if (((ref4 = this.userConfig) != null ? ref4.temperature : void 0) != null) {
        sendConfig.temperature = this.userConfig.temperature;
      }
      if (((ref5 = this.userConfig) != null ? ref5.stop : void 0) != null) {
        sendConfig.stop = this.userConfig.stop;
      }
      if (((ref6 = this.userConfig) != null ? ref6.maxToken : void 0) != null) {
        sendConfig.max_tokens = this.userConfig.maxToken;
      }
      //config配置工具调用
      if (config.tools) {
        sendConfig.tools = config.tools;
      }
      if (config.toolChoice) {
        sendConfig.tool_choice = config.toolChoice;
      }
      if (config.thinkControl === true) {
        sendConfig.enable_thinking = config.enableThinking ? true : false;
        sendConfig.reasoning_effort = config.thinkStrength;
      }
      // 调试：将请求报文写入 tmp 目录 (增加防抖避免频繁写入)
      writeDebugConfig(JSON.stringify(sendConfig, null, 2));
      if (!(streamFn || ((ref7 = this.userConfig) != null ? ref7.stream : void 0))) {
        //发起请求
        completion = (await this.openAi.chat.completions.create(sendConfig, {
          signal: this.abortController.signal
        }));
        if (!(completion != null ? (ref8 = completion.choices) != null ? (ref9 = ref8[0]) != null ? ref9.message : void 0 : void 0 : void 0)) {
          throw new Error("大模型接口请求失败", completion);
        }
        reply = completion.choices[0].message.content;
        reasoning = completion.choices[0].message.reasoning_content || "";
        toolCalls = (ref10 = completion.choices[0].message) != null ? ref10.tool_calls : void 0;
        if (completion.usage) {
          promptT = this.usage.promptTokens = completion.usage.prompt_tokens;
          totalT = this.usage.totalTokens = completion.usage.total_tokens;
          completionT = this.usage.completionTokens = completion.usage.completion_tokens;
          cachedT = this.usage.cachedTokens = ((ref11 = completion.usage.prompt_tokens_details) != null ? ref11.cached_tokens : void 0) || 0;
          if (this.stageTotalTokens == null) {
            this.stageTotalTokens = 0;
          }
          this.stageTotalTokens += totalT;
          //aiList[modelIndex].preTokens = Number(aiList[modelIndex].preTokens) - Number(@usage.totalTokens)
          //await options.set "ai_aiList",aiList
          if (config.onTokenChange) {
            await config.onTokenChange(this, {
              promptT: promptT,
              completionT: completionT,
              totalT: totalT,
              cachedT: cachedT
            });
          }
        } else {
          console.log("警告：大模型没有返回token使用信息，启动防呆累加");
          estimateTokens = (text) => {
            var en, ref12, zh;
            if (!text) {
              return 0;
            }
            zh = ((ref12 = text.match(/[\u4e00-\u9fa5]/g)) != null ? ref12.length : void 0) || 0;
            en = text.length - zh;
            return Math.ceil(zh * 1.5 + en * 0.3);
          };
          promptStr = ((function() {
            var j, len, ref12, results;
            ref12 = sendConfig.messages;
            results = [];
            for (j = 0, len = ref12.length; j < len; j++) {
              msg = ref12[j];
              results.push(msg.content);
            }
            return results;
          })()).join("\n");
          estTokens = estimateTokens(promptStr) + estimateTokens(reply);
          if (this.stageTotalTokens == null) {
            this.stageTotalTokens = 0;
          }
          this.stageTotalTokens += estTokens;
        }
      } else {
        completion = (await this.openAi.chat.completions.create(sendConfig, {
          signal: this.abortController.signal
        }));
        fullReplys = [];
        fullReasonings = [];
        fullToolCalls = [];
        replyChunk = "";
        reasoningChunk = "";
        doneChunk = null;
        for await (chunk of completion) {
          // 检查是否已停止，如果已停止则立即退出循环
          //if @stop
          //  break
          await (async(chunk) => {
            var deltaToolCalls, index, j, len, toolCallChunk;
            //console.log JSON.stringify(chunk)
            doneChunk = chunk;
            // 拼接并执行回调
            if (Array.isArray(chunk.choices) && chunk.choices.length > 0) {
              // 初始化本轮片段内容
              replyChunk = chunk.choices[0].delta.content || "";
              reasoningChunk = chunk.choices[0].delta.reasoning_content || "";
              deltaToolCalls = chunk.choices[0].delta.tool_calls;
              // 拼接回复
              if (replyChunk) {
                fullReplys.push(replyChunk);
              }
              // 拼接推理内容 (Reasoning Content)
              if (reasoningChunk) {
                fullReasonings.push(reasoningChunk);
              }
              // 拼接工具调用
              if (deltaToolCalls) {
                for (index = j = 0, len = deltaToolCalls.length; j < len; index = ++j) {
                  toolCallChunk = deltaToolCalls[index];
                  ((toolCallChunk) => {
                    var ref12, ref13, tmpIndex;
                    tmpIndex = toolCallChunk.index || index;
                    if (fullToolCalls[tmpIndex] == null) {
                      fullToolCalls[tmpIndex] = {
                        ...toolCallChunk,
                        function: {
                          name: "",
                          arguments: ""
                        }
                      };
                    }
                    if ((ref12 = toolCallChunk.function) != null ? ref12.name : void 0) {
                      fullToolCalls[tmpIndex].function.name = toolCallChunk.function.name;
                    }
                    if ((ref13 = toolCallChunk.function) != null ? ref13.arguments : void 0) {
                      return fullToolCalls[tmpIndex].function.arguments += toolCallChunk.function.arguments;
                    }
                  })(toolCallChunk);
                }
              }
              // 执行回调
              if (streamFn && (replyChunk || reasoningChunk)) {
                return (await streamFn({
                  aiAsk: this,
                  chunk: chunk,
                  replyChunk: replyChunk,
                  reasoningChunk: reasoningChunk
                }));
              }
            }
          })(chunk);
        }
        if (doneChunk != null ? doneChunk.usage : void 0) {
          this.usage.promptTokens = doneChunk.usage.prompt_tokens;
          this.usage.totalTokens = doneChunk.usage.total_tokens;
          this.usage.completionTokens = doneChunk.usage.completion_tokens;
          this.usage.cachedTokens = ((ref12 = doneChunk.usage.prompt_tokens_details) != null ? ref12.cached_tokens : void 0) || 0;
          promptT += this.usage.promptTokens;
          totalT += this.usage.totalTokens;
          completionT += this.usage.completionTokens;
          cachedT += this.usage.cachedTokens;
          if (this.stageTotalTokens == null) {
            this.stageTotalTokens = 0;
          }
          this.stageTotalTokens += totalT;
          //aiList[modelIndex].preTokens = Number(aiList[modelIndex].preTokens) - Number(@usage.totalTokens)
          //await options.set "ai_aiList",aiList
          if (config.onTokenChange) {
            await config.onTokenChange(this, {
              promptT: promptT,
              completionT: completionT,
              totalT: totalT,
              cachedT: cachedT
            });
          }
        } else {
          console.log("警告：流模式，大模型没有返回token使用信息，启动防呆累加");
          estimateTokens = (text) => {
            var en, ref13, zh;
            if (!text) {
              return 0;
            }
            zh = ((ref13 = text.match(/[\u4e00-\u9fa5]/g)) != null ? ref13.length : void 0) || 0;
            en = text.length - zh;
            return Math.ceil(zh * 1.5 + en * 0.3);
          };
          promptStr = ((function() {
            var j, len, ref13, results;
            ref13 = sendConfig.messages;
            results = [];
            for (j = 0, len = ref13.length; j < len; j++) {
              msg = ref13[j];
              results.push(msg.content);
            }
            return results;
          })()).join("\n");
          replyText = fullReplys.join("");
          estTokens = estimateTokens(promptStr) + estimateTokens(replyText);
          if (this.stageTotalTokens == null) {
            this.stageTotalTokens = 0;
          }
          this.stageTotalTokens += estTokens;
        }
        reply = fullReplys.join("");
        reasoning = fullReasonings.join("");
        toolCalls = fullToolCalls;
      }
      // --- 模式 4：原生工具外壳拦截 (Inbound Normalization for Mode 4) ---
      if (config.msgProtocolConfig.toolsMode === 4 && (toolCalls != null ? toolCalls.length : void 0) > 0) {
        templateCall = toolCalls.find((t) => {
          var ref13;
          return ((ref13 = t.function) != null ? ref13.name : void 0) === "sendTemplate";
        });
        if (templateCall) {
          // 将工具调用的参数直接作为 reply 原始字符串，以便后续 Joi 校验
          reply = templateCall.function.arguments;
          // 清除 toolCalls 数组，实现“嫁接”，让系统和 AI 记忆认为这是普通消息
          toolCalls = [];
        }
      }
      // 如果 AI 回复中包含 Markdown 图片，自动下载并转存
      assistantAttachments = [];
      if (typeof reply === 'string' && this.mediaDir) {
        imgRegex = /!\[([^\]]*)\]\((https?:\/\/[^\)]+)\)/g;
        matches = [];
        while ((match = imgRegex.exec(reply)) !== null) {
          matches.push(match);
        }
        if (matches.length > 0) {
          for (j = 0, len = matches.length; j < len; j++) {
            match = matches[j];
            try {
              imgUrl = match[2];
              id = idTool.get("image");
              // 自动获取后缀名
              ext = ".png";
              if (imgUrl.split('?')[0].match(/\.(jpg|jpeg|png|gif|webp)$/i)) {
                ext = imgUrl.split('?')[0].match(/\.(jpg|jpeg|png|gif|webp)$/i)[0];
              }
              filename = `${id}${ext}`;
              uploadPath = pathLib.resolve(this.mediaDir, filename);
              await fs.ensureDir(this.mediaDir);
              // 下载并保存
              imgResponse = (await axios.get(imgUrl, {
                responseType: 'arraybuffer'
              }));
              await fs.writeFile(uploadPath, Buffer.from(imgResponse.data));
              assistantAttachments.push({
                id: filename,
                url: `/attachment/${filename}`,
                type: 'image'
              });
              // 替换为标签
              reply = reply.replace(match[0], `[attachid:${filename}]`);
            } catch (error1) {
              e = error1;
              console.error("归一化处理图片失败:", e);
            }
          }
        }
      }
      console.log("模式2工具调用情况", toolCalls);
      
      // 清洗AI可能幻觉复读的元数据标签，防止套娃叠加
      //reply = reply.replace(/<readOnlyMetaData>[\s\S]*?<\/readOnlyMetaData>/g, "").trim()
      this.addAsk(this.name, "assistant", reply, {
        promptTokens: promptT,
        completionTokens: completionT,
        totalTokens: totalT,
        cachedTokens: cachedT,
        reasoning: reasoning,
        toolCalls: toolCalls,
        attachments: assistantAttachments,
        group: "agent",
        listId: config.listId
      });
      return this.asks.at(-1);
    } catch (error1) {
      err = error1;
      throw err;
    }
  }

  //快速提问
  async ask(user, role, msg, config) {
    var err;
    try {
      this.addAsk(user, role, msg);
      return (await this.sendAsk(null, config));
    } catch (error1) {
      err = error1;
      throw err;
    }
  }

  async sendAskByMsgProtocol(config = {}) {
    /*Object.entries(call.arguments).map(([key,value])=>"#{key}:#{value}").join("\n")*/
    var aiReply, allTools, ask, deferFn, deferredFns, e, err, errTip, errorMsg, extJoiError, extJsonConfigStr, i, idx, isLast, j, joiError, joiSchema, jsonErr, l, lastWarningIdx, len, len1, len2, len3, len4, match, matchReadOnlyMetaData, n, o, p, parseError, parsedConfig, prePareCallStr, q, r, realUserMsgCount, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, reply, replyJSON, ret, returnJoi, secondErr, shouldWarn, sysReturns, sysReturnsStr, time, tip, toolCall, toolCallDuration, toolCallGroupId, toolCallStartTime, toolCallSuccess, toolTipObj, truncatedFns, validateOutput;
    try {
      //console.log "发送前",@messages
      this.replying = true;
      if (this.stop) {
        this.replying = false;
      }
      if (config.beforeRun) {
        await config.beforeRun(this);
      }
      if (this.stop) {
        return;
      }
      //等待
      await new Promise((res) => {
        return setTimeout(res, 200);
      });
      // 工具由外部注入（config.tools 为扁平数组，每个 tool 带 type 属性）
      allTools = config.tools || [];
      toolTipObj = {
        sysCall: allTools.filter((t) => {
          return t.type === "sysCall" || t.type === "appCall";
        }).map(createToolTip),
        usrCall: allTools.filter((t) => {
          return t.type === "usrCall";
        }).map(createToolTip),
        aiCall: allTools.filter((t) => {
          return t.type === "aiCall";
        }).map(createToolTip)
      };
      // 检查 Token 阶段限额并做提醒
      console.log(config != null ? config.tokenCompressSwitch : void 0, "压缩上下文");
      console.log("压缩上下文开关", config != null ? config.tokenCompressSwitch : void 0);
      if (this.stageTotalTokens > 1000000 && (config != null ? config.tokenCompressSwitch : void 0)) {
        lastWarningIdx = -1;
        for (i = j = ref = this.asks.length - 1; j >= 0; i = j += -1) {
          ask = this.asks[i];
          if (ask.role === "user" && ask.user === "系统" && ask.content.includes("compressContext") && ask.content.includes("tokens")) {
            lastWarningIdx = i;
            break;
          }
        }
        shouldWarn = false;
        if (lastWarningIdx === -1) {
          shouldWarn = true;
        } else {
          realUserMsgCount = 0;
          for (idx = l = ref1 = lastWarningIdx, ref2 = this.asks.length - 1; (ref1 <= ref2 ? l <= ref2 : l >= ref2); idx = ref1 <= ref2 ? ++l : --l) {
            ask = this.asks[idx];
            if (ask.role === "user" && ask.user !== "系统" && ask.user !== "系统通讯中枢") {
              realUserMsgCount++;
            }
          }
          if (realUserMsgCount >= 5) {
            shouldWarn = true;
          }
        }
        if (shouldWarn) {
          ask = this.addAsk("系统", "user", `⚠️ 系统提醒：当前开发阶段累计已消耗 ${this.stageTotalTokens} tokens。为保证响应效率及优化缓存性能，请务必立即调用「阶段清理并压缩上下文 (compressContext)」工具对当前做阶段性总结并清空历史会话。注意：此操作会彻底清除之前所有的上下文和工具调用细节！如果你正在处理连贯的关键任务或刚读取了重要线索，请在当前任务闭环后再执行清理，并务必利用 summary 备忘录将关键记忆带到下一阶段！`);
          if (config.onResponse) {
            await config.onResponse(ask);
          }
        }
      }
      
      //开始逻辑
      this.fnCallCachePoolTick();
      this.messages = this.prepareMessages(true, config, config.toolTipObj || toolTipObj);
      if (config.retry == null) {
        config.retry = 0;
      }
      aiReply = (await this.sendAsk(config.streamFn || null, {
        onSendAskBefore: config.onSendAskBefore, //sendAsk之前判定preToken用
        onTokenChange: config.onTokenChange, //token变化计算preToken用
        listId: config.listId, // 修复：显式传递 listId，确保 aiReply 正确携带所属列表 ID
        useMsgProtocol: true,
        msgProtocolConfig: config,
        messages: this.messages,
        ...(config.toolsMode === 1 ? {
          jsonObject: true
        } : void 0),
        ...(config.toolsMode === 2 || config.toolsMode === 5 ? {
          tools: allTools.map(createStdToolTip),
          toolChoice: "auto"
        } : void 0),
        // Mode 2 不传 jsonSchema，让 AI 自由输出文本，解析层自动包装
        //jsonSchema: joiToJSON(sendTemplate.joi(config.toolsMode))
        ...(config.toolsMode === 3 ? {
          jsonSchema: joiToJSON(sendTemplate.joi(config.toolsMode))
        } : void 0),
        ...(config.toolsMode === 4 ? {
          tools: [
            {
              type: "function",
              function: {
                name: "sendTemplate",
                description: "发送工具。所有操作的总入口，每次对话【必须】调用本工具来回复用户或调用函数。其它回复入口均关闭。",
                parameters: joiToJSON(sendTemplate.joi(config.toolsMode)) //4号工具模式
              }
            }
          ]
        } : void 0),
        //toolChoice: { type: "function", function: { name: "sendTemplate" } }
        enableThinking: config.enableThinking,
        thinkControl: config.thinkControl,
        thinkStrength: config.thinkStrength
      }));
      
      // 如果是因为用户主动停止导致的 sendAsk 结束，则不再进行后续解析和校验逻辑，防止解析残缺 JSON 报错并触发重试
      if (this.stop) {
        this.replying = false;
        return;
      }
      //不管格式是否正确，都先发送一条到前端，这样方便调试。这条消息必须是原始消息
      if (config.onResponse) {
        await config.onResponse(aiReply);
      }
      reply = aiReply.content;
      replyJSON = null;
      
      //检查消息格式是否正确
      joiError = parseError = null;
      replyJSON = null;
      try {
        if (config.toolsMode === 5) {
          replyJSON = {};
          match = aiReply.content.match(/<extJsonConfig>([\s\S]+?)<\/extJsonConfig>/);
          matchReadOnlyMetaData = aiReply.content.match(/readOnlyMetaData|readOnleyMetaData|元数据 供阅读，禁止回复携带/g);
          extJsonConfigStr = match != null ? match[1] : void 0;
          errTip = "";
          if (extJsonConfigStr) {
            try {
              parsedConfig = JSON.parse(extJsonConfigStr.trim());
              joiSchema = sendTemplate.joi(config.toolsMode);
              validateOutput = joiSchema.validate(parsedConfig, {
                abortEarly: false
              });
              extJoiError = validateOutput.error;
              if (extJoiError) {
                errTip = "提示 extJsonConfig字段Joi校验错误，附加字段配置将不生效：" + extJoiError.details.map(function(d) {
                  return d.message;
                }).join('; ');
              }
            } catch (error1) {
              err = error1;
              errTip = "提示 extJsonConfig字段JSON.parse错误，附加字段配置将不生效：" + err.message;
            }
          }
          if (matchReadOnlyMetaData && matchReadOnlyMetaData.length > 0) {
            errTip = errTip + "警告：回复中出现了禁止携带的readOnlyMetaData的元数据标签，请勿模仿，携带任何系统的元数据。你只需发送回复用户的内容";
          }
          if (errTip) {
            ask = this.addAsk("系统通讯中枢", "user", errTip, {
              isSystem: 1,
              group: "tip"
            });
            if (config.onResponse) {
              await config.onResponse(ask);
            }
          } else {
            if (parsedConfig != null ? parsedConfig.note : void 0) {
              replyJSON.note = parsedConfig.note;
            }
          }
        } else {
          // 处理空回复的情况（通常出现在原生工具调用时，模型可能不输出正文 JSON）
          //这里只负责报错，由ioApi_chat.js负责解析和渲染数据
          if (!(reply != null ? reply.trim() : void 0) && ((ref3 = aiReply.toolCalls) != null ? ref3.length : void 0) > 0) {
            replyJSON = { //模式2的标准工具模式，不需要传note和tasks字段
              mind: "执行函数...",
              mood: 5,
              content: "执行函数...",
              playFace: "无表情",
              faceAction: "none",
              graph: "我已知晓"
            };
          } else {
            try {
              // 优先尝试直接解析
              replyJSON = JSON.parse(reply);
            } catch (error1) {
              jsonErr = error1;
              try {
                // 增加容错：尝试从杂乱文本或 Markdown 中提取 JSON 结构
                replyJSON = JSON.parse(tryExtractJSON(reply));
                console.warn("[aiAsk] JSON 直接解析失败，但通过过滤提取成功。");
              } catch (error1) {
                secondErr = error1;
                throw jsonErr; // 非 Mode 2 抛出原始错误，走原有重试逻辑
              }
            }
          }
          joiSchema = sendTemplate.joi(config.toolsMode);
          validateOutput = joiSchema.validate(replyJSON, {
            abortEarly: false
          });
          joiError = validateOutput.error;
        }
        if (aiReply.toolCalls) { //如果使用了tools参数，把工具调用转换为sysCalls
          if (replyJSON.sysCalls == null) {
            replyJSON.sysCalls = [];
          }
          ref4 = aiReply.toolCalls;
          for (n = 0, len = ref4.length; n < len; n++) {
            toolCall = ref4[n];
            replyJSON.sysCalls.push({
              id: toolCall.function.name,
              call_id: toolCall.id,
              type: "function_call",
              name: toolCall.function.name,
              arguments: JSON.parse(toolCall.function.arguments)
            });
          }
        }
      } catch (error1) {
        err = error1;
        parseError = "调用JSON.parse解析错误：" + err;
      }
      if (joiError || parseError) {
        console.log("解析错误", joiError, parseError);
        console.log("重试次数", config.retry);
        console.log("=====");
        returnJoi = joiError ? "joi校验错误" + joiError.details.map(function(d) {
          return d.message;
        }).join('; ') : parseError;
        // 如果本轮有工具调用，通过还原工具结果来报回错误，避免 400 错误并保护执行安全
        if (((ref5 = aiReply.toolCalls) != null ? ref5.length : void 0) > 0) {
          errorMsg = config.toolsMode === 5 ? `⚠️ 系统拦截：工具参数JSON解析错误（${returnJoi}）` : `⚠️ 系统拦截：消息正文JSON错误（joi校验错误: ${returnJoi}）请根据通讯协议返回stringify后的标准json格式，禁止携带元数据`;
          ref6 = aiReply.toolCalls;
          for (o = 0, len1 = ref6.length; o < len1; o++) {
            toolCall = ref6[o];
            ask = this.addAsk(toolCall.function.name, "tool", errorMsg, {
              tool_call_id: toolCall.id
            });
          }
          if (config.onResponse) {
            await config.onResponse(ask);
          }
          // 直接进入递归重试
          if (config.retry < 4) {
            config.retry++;
            await this.sendAskByMsgProtocol({...config});
            this.replying = false;
            return;
          } else {
            tip = "ai返回错误超出系统限制";
            ask = this.addAsk("系统通讯中枢", "user", tip, {
              isSystem: 1,
              retry: config.retry,
              joi: returnJoi,
              group: "tip"
            });
            if (config.onResponse) {
              await config.onResponse(ask);
            }
            config.retry = 0;
            this.replying = false; //递归不需要回归
            return;
          }
        } else {
          // 如果没有工具调用，保留原有的 User 消息报错模式
          tip = `返回JSON错误，请严格按通讯协议构建被能够被JSON.parse的标准JSON字符串，禁止携带元数据，错误详见joi字段，重试${config.retry + 1}/4`;
          ask = this.addAsk("系统通讯中枢", "user", tip, {
            isSystem: 1,
            retry: config.retry,
            joi: returnJoi,
            group: "tip"
          });
          if (config.onResponse) {
            await config.onResponse(ask);
          }
          if (config.retry < 4) {
            config.retry++;
            await this.sendAskByMsgProtocol({
              ...config,
              onResponse: async(reply) => {
                if (config.onResponse) {
                  return (await config.onResponse(reply));
                }
              }
            });
            this.replying = false; //递归不需要回归
            return;
          } else {
            tip = "ai返回错误超出系统限制";
            ask = this.addAsk("系统通讯中枢", "user", tip, {
              isSystem: 1,
              retry: config.retry,
              joi: returnJoi,
              group: "tip"
            });
            if (config.onResponse) {
              await config.onResponse(ask);
            }
            config.retry = 0;
            this.replying = false; //递归不需要回归
            return;
          }
        }
      }
      config.retry = 0; //重置
      
      //处理任务
      if (replyJSON.tasks && (config != null ? config.onTaskChange : void 0)) {
        try {
          await config.onTaskChange(this, replyJSON.tasks);
        } catch (error1) {
          e = error1;
          // 钩子业务校验失败，触发重试喵
          if (config.retry == null) {
            config.retry = 0;
          }
          if (config.retry < 4) {
            config.retry++;
            console.log(`任务校验失败，准备重试第 ${config.retry} 次`, e.message);
            this.addAsk("系统", "user", `任务同步失败：${e.message}\n请检查任务 ID 是否正确，并重新输出完整的 JSON 回复。`, {
              group: "tip",
              isSystem: 1
            });
            await this.sendAskByMsgProtocol(config);
            this.replying = false;
            return;
          } else {
            console.error("任务校验失败且重试次数耗尽", e.message);
          }
        }
      }
      //处理记忆
      if (replyJSON.note) {
        this.memory = {
          id: aiReply.id,
          listId: aiReply.listId,
          time: aiReply.time,
          note: replyJSON.note,
          content: `[列表id：${aiReply.listId}][消息id:${aiReply.id}][时间:${aiReply.time}]\n` + (typeof replyJSON.note === 'string' ? replyJSON.note : yaml.dump(replyJSON.note))
        };
        this.memorys.push(this.memory);
        await this._rollMemory(config); //记忆裁剪和总结
        if (config != null ? config.onMemoryChange : void 0) {
          await config.onMemoryChange(this, this.memorys);
        }
      }
      //处理函数调用
      if (((ref7 = replyJSON.sysCalls) != null ? ref7.length : void 0) > 0) {
        time = new Date();
        if (config.sysCallCount == null) {
          config.sysCallCount = 0;
        }
        if (config.sysCallCount < 100) {
          console.log("触发函数调用");
          config.sysCallCount++;
          // 生成工具调用组ID和记录开始时间
          toolCallGroupId = `tcg_${Date.now()}`;
          toolCallStartTime = Date.now();
          prePareCallStr = `\`\`\`\n${yaml.dump(replyJSON.sysCalls)}\n\`\`\``;
          ask = this.addAsk("系统通讯中枢", "user", `准备调用函数，本消息不被发送\n${prePareCallStr}`.trim(), {
            isSystem: 1,
            ignore: 1,
            group: "tip",
            title: "准备调用函数，本消息不被发送",
            toolCallGroupId: toolCallGroupId,
            toolCallStage: "prepare",
            sysCalls: replyJSON.sysCalls
          });
          if (config.onResponse) {
            await config.onResponse(ask);
          }
          deferredFns = [];
          sysReturns = (await this.sysCallRunFns(replyJSON.sysCalls, allTools, {
            listId: config.listId,
            allCalls: replyJSON.sysCalls,
            toolCallGroupId,
            aiAskInstance: this,
            deferredFns,
            onResponse: config.onResponse,
            aiReply,
            config
          }));
          // 检查是否有内容超出限制，并处理截断与 UI 提示
          truncatedFns = [];
          for (p = 0, len2 = sysReturns.length; p < len2; p++) {
            ret = sysReturns[p];
            // 1. 强制类型转换为字符串 (这对 toolsMode=2 甚至 Mode 3 的稳定性至关重要)
            // 如果是对象，转为 JSON 字符串；如果是其他，转为 String
            if (typeof ret.output !== 'string') {
              ret.output = String(ret.output);
            }
            // 2. 长度安全检查与截断
            if (ret.output.length > 20000) {
              // 实施截断
              ret.output = ret.output.slice(0, 20000) + "...(已截断0-20000字)";
              truncatedFns.push(`【${ret.name || ret.id}】`);
            }
          }
          if (truncatedFns.length > 0) {
            ask = this.addAsk("系统通讯中枢", "user", `⚠️ 警告：检测到函数 ${truncatedFns.join(', ')} 输出超过安全限制（20000字符），内容已被自动截断以保护会话性能。该提示不会发送给 AI。`, {
              isSystem: 1,
              ignore: 1,
              group: "tip",
              title: "函数输出截断警告",
              toolCallGroupId: toolCallGroupId
            });
            if (config.onResponse) {
              await config.onResponse(ask);
            }
          }
          // 计算执行时长和判断是否成功
          toolCallDuration = Date.now() - toolCallStartTime;
          toolCallSuccess = sysReturns.every(function(ret) {
            return !ret.error;
          });
          // 同步加入缓存池，避免下一回合才能获取到索引
          sysReturns.forEach((ret) => {
            return this.fnCallCachePoolAdd(ret);
          });
          if (config.toolsMode === 2 || config.toolsMode === 5) { //标准工具模式需要用指定tool角色，有多条工具调用消息，在最后一条加信息
            for (i = q = 0, len3 = sysReturns.length; q < len3; i = ++q) {
              ret = sysReturns[i];
              isLast = i === sysReturns.length - 1;
              ask = this.addAsk("系统通讯中枢", "tool", ret.output + `${isLast && enableToolFold ? "下一轮对话这些结果将被折叠，请对关键信息记好笔记" : ""}`, {
                tool_call_id: ret.call_id,
                name: ret.id,
                group: "tip",
                isSystem: 1,
                toolCallGroupId: toolCallGroupId,
                toolCallStage: isLast ? "done" : "executing",
                ...(isLast ? {
                  toolCallDuration: toolCallDuration,
                  toolCallSuccess: toolCallSuccess
                } : void 0)
              });
              if (config.onResponse) {
                await config.onResponse(ask);
              }
            }
          } else {
            ask = this.addAsk("系统通讯中枢", "user", `函数执行完毕
  \`\`\`\n${yaml.dump(sysReturns)}\n\`\`\`
下一轮对话该结果将被折叠，请对关键信息记好笔记`.trim(), {
              isSystem: 1,
              sysReturns: sysReturns,
              group: "tip",
              title: "函数执行完毕",
              toolCallGroupId: toolCallGroupId,
              toolCallStage: "done",
              toolCallDuration: toolCallDuration,
              toolCallSuccess: toolCallSuccess
            });
            if (config.onResponse) {
              await config.onResponse(ask);
            }
          }
          //处理函数调用，缓存最近10条
          sysReturnsStr = (function(output) {
            sysReturns.forEach(function(ret) {
              return output += `[name:${ret.name}][id:${ret.id}][call_id:${ret.call_id}]\n${ret.output}\n`;
            });
            return output;
          })("");
          this.fnCallOutput = `[列表id：${aiReply.listId}][消息id:${aiReply.id}][时间:${aiReply.time}]\n${sysReturnsStr}`;
          this.fnCallOutputs.push(this.fnCallOutput);
          if (this.fnCallOutputs.length > 10) {
            this.fnCallOutputs.shift();
          }
// 在协议安全窗口内，统一执行工具注册的延迟函数（如 aiSendMessage）
          for (r = 0, len4 = deferredFns.length; r < len4; r++) {
            deferFn = deferredFns[r];
            await deferFn();
          }
          await this.sendAskByMsgProtocol({
            ...config,
            onResponse: config.onResponse
          });
          return;
        } else {
          ask = this.addAsk("系统通讯中枢", "user", "函数反复调用超限，请先中断等待用户继续发起", {
            isSystem: 1,
            group: "tip",
            title: "函数调用超限"
          });
          if (config.onResponse) {
            await config.onResponse(ask);
          }
          await this.sendAskByMsgProtocol({
            ...config,
            onResponse: config.onResponse
          });
          return;
        }
      }
      this.replying = false;
      if (config.endRun) {
        return (await config.endRun(this));
      }
    } catch (error1) {
      err = error1;
      this.replying = false;
      if (config.endRun) {
        await config.endRun(this);
      }
      throw err;
    }
  }

  stopRun() {
    this.abortController.abort();
    return this.stop = true;
  }

  noStopRun() {
    this.abortController = new AbortController();
    return this.stop = false;
  }

  async sysCallRunFns(sysCalls, sysAllTools, metaData = {}) {
    var call, err, fn, j, len, returnStr, sysReturns;
    sysReturns = [];
    returnStr = "";
    for (j = 0, len = sysCalls.length; j < len; j++) {
      call = sysCalls[j];
      fn = sysAllTools.find((tool) => {
        return tool.id === call.id;
      });
      if (!fn) {
        returnStr = `找不到函数 ${call.name} ${call.id}`;
      } else {
        try {
          returnStr = (await fn.fn(call.arguments, metaData));
          if (Object.prototype.toString.call(returnStr) === "[object Object]") {
            returnStr = JSON.stringify(returnStr);
          } else if (typeof returnStr === "string") {
            returnStr = String(returnStr);
          } else {
            throw new Error("工具函数损坏，返回了非字符串或对象数据已被系统拦截");
          }
        } catch (error1) {
          err = error1;
          console.log(err, String(err));
          returnStr = String(err);
        }
      }
      sysReturns.push({
        type: "function_call_output",
        call_id: call.call_id,
        name: call.name,
        id: call.id,
        output: returnStr,
        arguments: call.arguments
      });
    }
    return sysReturns;
  }

  fnCallCachePoolAdd(sysReturn) {
    var cacheid, keys;
    // 使用唯一的 call_id 作为缓存池的 Key，避免生成新 ID 导致的重复入池
    cacheid = sysReturn.call_id;
    if (!this.fnCallCachePool[cacheid]) {
      keys = Object.keys(this.fnCallCachePool);
      if (keys.length >= 10) {
        delete this.fnCallCachePool[keys[0]];
      }
      this.fnCallCachePool[cacheid] = {
        cacheid: cacheid,
        name: sysReturn.name,
        arguments: sysReturn.arguments,
        output: sysReturn.output,
        count: 0
      };
    }
    return this.fnCallCachePool[cacheid];
  }

  fnCallCachePoolRemove(cacheid) {
    return delete this.fnCallCachePool[cacheid];
  }

  fnCallCachePoolTick() {
    var id, item, ref, results;
    ref = this.fnCallCachePool;
    results = [];
    for (id in ref) {
      item = ref[id];
      if (item.count > 0) {
        results.push(item.count--);
      } else {
        results.push(void 0);
      }
    }
    return results;
  }

  // ========== 记忆管理 ==========

    // 双重滚动总结：超过100条时裁剪并按需生成摘要
  async _rollMemory(config) {
    var completion, err, ref, ref1, ref2, ref3, ref4, rollContent, summaryIdx, summaryText;
    if (!(this.memorys.length >= 100)) {
      return;
    }
    summaryIdx = this.memorys.findIndex((m) => {
      return m.isSummary;
    });
    if (!(summaryIdx > 0)) {
      // 没有总结 或 总结已滑到首位 → 删前51条，生成新摘要
      // 1. 提取前 51 条记录的内容（含旧总结）
      rollContent = this.memorys.slice(0, 51).map((m) => {
        if (m.isSummary) {
          return `[旧总结] ${m.content}`;
        } else {
          return m.content;
        }
      }).join("\n");
      
      // 2. 执行物理裁剪 (100 - 51 = 49条剩余)
      this.memorys.splice(0, 51);
      if (config != null) {
        if (typeof config.onRollMemory === "function") {
          config.onRollMemory("start");
        }
      }
      try {
        completion = (await this.openAi.chat.completions.create({
          model: this.aiConfig.model,
          messages: [
            {
              role: "system",
              content: "你是记忆压缩助手，只输出摘要，不做任何多余对话。"
            },
            {
              role: "user",
              content: `系统即将裁剪你的记忆，为了避免遗忘，请小心谨慎得对下面的记忆笔记做个信息密度极高的压缩，以日记形式呈现。
注意如果总结不到位，你会失忆哦【！！！】
注意事情发生的时间、地点、人物、起因、经过、结果。注意记录任务目标，任务过程和任务完成情况。
要求：
1. 保留所有关键事实、数字、文件名、决策结论
2. 删除寒暄、重复内容、过渡语句
3. 如果已有旧总结，请将旧总结的信息融合进新总结中
5. 总字数控制在800字以内
6. 必须以第一人称（我）来记录
范例：时间xxx，今天心情不错，很开心，用户说今天电脑故障了，让我帮忙排查下，我通故终端执行xxx,xxx,xxx等命令，发现xxx...(详细过程和重点)...最后通过xxx帮助用户解决了问题。用户很感谢我，太开心啦！
=== 记忆笔记 ===
${rollContent}`.trim()
            }
          ],
          max_tokens: 1000,
          temperature: 0.3
        }));
        summaryText = ((ref = completion.choices) != null ? (ref1 = ref[0]) != null ? (ref2 = ref1.message) != null ? (ref3 = ref2.content) != null ? ref3.trim() : void 0 : void 0 : void 0 : void 0) || "";
        if (completion.usage) {
          this.usage.promptTokens += completion.usage.prompt_tokens || 0;
          this.usage.completionTokens += completion.usage.completion_tokens || 0;
          this.usage.totalTokens += completion.usage.total_tokens || 0;
          if (config != null ? config.onTokenChange : void 0) {
            await config.onTokenChange(this, {
              promptT: completion.usage.prompt_tokens || 0,
              completionT: completion.usage.completion_tokens || 0,
              totalT: completion.usage.total_tokens || 0,
              cachedT: 0
            });
          }
        }
        if (summaryText) {
          // 3. 将新总结插入头部 (1 + 49 = 50条)
          this.memorys.unshift({
            id: `summary_${Date.now()}`,
            isSummary: true,
            listId: config.listId || 0,
            time: new Date().toISOString(),
            note: `【滚动总结】${summaryText}`,
            content: `[列表id：${config.listId || 0}][消息id:summary][时间:${new Date().toISOString()}]\n【滚动总结】${summaryText}`
          });
          console.log(`滚动总结生成成功 (${summaryText.length}字, ${((ref4 = completion.usage) != null ? ref4.total_tokens : void 0) || '?'}tokens)`);
        } else {
          console.warn("滚动总结返回为空，跳过插入");
        }
        return config != null ? typeof config.onRollMemory === "function" ? config.onRollMemory("done") : void 0 : void 0;
      } catch (error1) {
        err = error1;
        console.error("滚动总结生成失败:", err);
        if (config != null) {
          if (typeof config.onRollMemory === "function") {
            config.onRollMemory("error");
          }
        }
        // 失败时仍插入一条提示，占住总结位
        return this.memorys.unshift({
          id: `summary_${Date.now()}`,
          isSummary: true,
          time: new Date().toISOString(),
          content: "记忆总结失败，请使用历史记录工具查询历史消息"
        });
      }
    } else {
      // 总结在中间，普通shift让总结自然向左漂移
      return this.memorys.shift();
    }
  }

});

// buildTasks 已移至 ioApiChat 或 getExtraInfo 处理喵
