// Generated by CoffeeScript 2.7.0
export default {
  joiSchemaFn: function() {
    return Joi.object({
      id: Joi.any().forbidden().description("禁止传入id避免和系统生成id混淆"),
      call: Joi.string().allow("").description("历史会话id，你可以针对某个id的历史会话进行点评，允许无"),
      quotes: Joi.array().items(Joi.string()).description("每个元素为历史会话id字符串。针对聊天情况，你也可引用一些历史会话，允许无"),
      mind: Joi.string().required().description("你的思考过程，不许空"),
      mood: Joi.number().min(0).max(10).required().description("1到10,你的心情值，值越大心情越好"),
      at: Joi.string().allow("").description("用户的用户名，可留空字串。表示是否需要@用户"),
      content: Joi.string().required().description("markdown字符串，思考后决定回复的内容，needReply为0将不会发出，不许空"),
      note: Joi.string().allow("").required().description("当前发生事情的完整记忆，不许空"),
      faceAction: Joi.string().valid("angry", "chrimas", "chrimasEye", "clenchedTeeth", "clenchedTeethAngry", "clenchedTeethEmbarrassed", "cryHappy", "crySad", "grin", "grinEmbarrassed", "grinHappy", "nervous", "pout", "poutEye", "poutSad", "poutSlacken", "sad", "slacken", "slackenMore", "smile", "smileEye").description("表态动作，请从中选一个"),
      sysCalls: Joi.array().items(Joi.object({
        id: Joi.string().required().description("函数的id"),
        call_id: Joi.string().required().description("调用id，同id的函数允许多次调用，用call_id区分，不能重复"),
        type: Joi.string().valid("function_call").required().description("调用类型"),
        name: Joi.string().required().description("函数名"),
        arguments: Joi.object().required().description("具名参数列表json，请据函数parameters填写，不许空")
      }).description("每个数组元素为对象")).description("调用系统函数数组，若有项目，下次请求将在sysReturns中返回函数输出，若为空填写空数组")
    }).required();
  },
  joiUserSchemaFn: function() {
    return Joi.object({
      id: Joi.string().description("会话id"),
      user: Joi.string().description("用户名"),
      role: Joi.string().description("角色，保留字段，暂时没用"),
      content: Joi.string().description("消息主体"),
      call: Joi.string().description("历史会话id，用户针对某个id的历史会话进行点评"),
      quotes: Joi.array().items(Joi.string()).description("每个元素为历史会话id字符串。用户引用了一些历史对话"),
      isSystem: Joi.number().valid(0, 1).description("0或1 是否是系统消息"),
      timestamp: Joi.string().description("时间戳"),
      time: Joi.string().description("格式化后的时间字符串"),
      memory: Joi.string().description("上次你回复中的笔记"),
      sysReturns: Joi.array().items(Joi.object({
        type: Joi.string().valid("function_call_output").description("类型"),
        call_id: Joi.string().description("调用id"),
        name: Joi.string().description("函数名"),
        id: Joi.string().description("函数id"),
        output: Joi.string().description("函数输出")
      })),
      retry: Joi.number().description("重试次数，若系统解析JSON失败将重试"),
      joi: Joi.string().description("若系统解析JSON失败，将返回用joi解析JSON的报错结果"),
      ext: Joi.object().description("扩展字段")
    });
  }
};
